[package]
name = "immich-sync"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/main.rs"

[[bin]]
name = "get-auth"
path = "src/get-auth/main.rs"

[dependencies]
dotenvy = "0.15.7"
openapi = {path = "immich-open-api"}
gphotos-api = {path = "photos-api/generated"}
tokio = { version = "1", features = ["full"] }
oauth2 = "5.0.0-alpha.4"
anyhow = "1.0.86"
url = "2.5.2"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
reqwest = "0.12.5"
