[package]
name = "immich-api"
version = "1.106.4"
authors = ["OpenAPI Generator team and contributors"]
description = "Immich API"
# Override this license by providing a License Object in the OpenAPI.
license = "Unlicense"
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
url = "^2.5"
uuid = { version = "^1.8", features = ["serde", "v4"] }
reqwest = { version = "^0.12", default-features=false, features = ["json", "multipart", "rustls-tls"] }
bytes = "1.6.0"
