/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlbumUserRole {
    #[serde(rename = "editor")]
    Editor,
    #[serde(rename = "viewer")]
    Viewer,

}

impl ToString for AlbumUserRole {
    fn to_string(&self) -> String {
        match self {
            Self::Editor => String::from("editor"),
            Self::Viewer => String::from("viewer"),
        }
    }
}

impl Default for AlbumUserRole {
    fn default() -> AlbumUserRole {
        Self::Editor
    }
}

