/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetJobName {
    #[serde(rename = "regenerate-thumbnail")]
    RegenerateThumbnail,
    #[serde(rename = "refresh-metadata")]
    RefreshMetadata,
    #[serde(rename = "transcode-video")]
    TranscodeVideo,

}

impl ToString for AssetJobName {
    fn to_string(&self) -> String {
        match self {
            Self::RegenerateThumbnail => String::from("regenerate-thumbnail"),
            Self::RefreshMetadata => String::from("refresh-metadata"),
            Self::TranscodeVideo => String::from("transcode-video"),
        }
    }
}

impl Default for AssetJobName {
    fn default() -> AssetJobName {
        Self::RegenerateThumbnail
    }
}

