/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetBulkUploadCheckResponseDto {
    #[serde(rename = "results")]
    pub results: Vec<models::AssetBulkUploadCheckResult>,
}

impl AssetBulkUploadCheckResponseDto {
    pub fn new(results: Vec<models::AssetBulkUploadCheckResult>) -> AssetBulkUploadCheckResponseDto {
        AssetBulkUploadCheckResponseDto {
            results,
        }
    }
}

