/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,

}

impl ToString for AssetOrder {
    fn to_string(&self) -> String {
        match self {
            Self::Asc => String::from("asc"),
            Self::Desc => String::from("desc"),
        }
    }
}

impl Default for AssetOrder {
    fn default() -> AssetOrder {
        Self::Asc
    }
}

