/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetMediaSize {
    #[serde(rename = "preview")]
    Preview,
    #[serde(rename = "thumbnail")]
    Thumbnail,

}

impl ToString for AssetMediaSize {
    fn to_string(&self) -> String {
        match self {
            Self::Preview => String::from("preview"),
            Self::Thumbnail => String::from("thumbnail"),
        }
    }
}

impl Default for AssetMediaSize {
    fn default() -> AssetMediaSize {
        Self::Preview
    }
}

