/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AudioCodec {
    #[serde(rename = "mp3")]
    Mp3,
    #[serde(rename = "aac")]
    Aac,
    #[serde(rename = "libopus")]
    Libopus,

}

impl ToString for AudioCodec {
    fn to_string(&self) -> String {
        match self {
            Self::Mp3 => String::from("mp3"),
            Self::Aac => String::from("aac"),
            Self::Libopus => String::from("libopus"),
        }
    }
}

impl Default for AudioCodec {
    fn default() -> AudioCodec {
        Self::Mp3
    }
}

