/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Colorspace {
    #[serde(rename = "srgb")]
    Srgb,
    #[serde(rename = "p3")]
    P3,

}

impl ToString for Colorspace {
    fn to_string(&self) -> String {
        match self {
            Self::Srgb => String::from("srgb"),
            Self::P3 => String::from("p3"),
        }
    }
}

impl Default for Colorspace {
    fn default() -> Colorspace {
        Self::Srgb
    }
}

