/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CqMode {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "cqp")]
    Cqp,
    #[serde(rename = "icq")]
    Icq,

}

impl ToString for CqMode {
    fn to_string(&self) -> String {
        match self {
            Self::Auto => String::from("auto"),
            Self::Cqp => String::from("cqp"),
            Self::Icq => String::from("icq"),
        }
    }
}

impl Default for CqMode {
    fn default() -> CqMode {
        Self::Auto
    }
}

