/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DuplicateDetectionConfig {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "maxDistance")]
    pub max_distance: f64,
}

impl DuplicateDetectionConfig {
    pub fn new(enabled: bool, max_distance: f64) -> DuplicateDetectionConfig {
        DuplicateDetectionConfig {
            enabled,
            max_distance,
        }
    }
}

