/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EntityType {
    #[serde(rename = "ASSET")]
    Asset,
    #[serde(rename = "ALBUM")]
    Album,

}

impl ToString for EntityType {
    fn to_string(&self) -> String {
        match self {
            Self::Asset => String::from("ASSET"),
            Self::Album => String::from("ALBUM"),
        }
    }
}

impl Default for EntityType {
    fn default() -> EntityType {
        Self::Asset
    }
}

