/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FaceDto {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl FaceDto {
    pub fn new(id: uuid::Uuid) -> FaceDto {
        FaceDto {
            id,
        }
    }
}

