/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageFormat {
    #[serde(rename = "jpeg")]
    Jpeg,
    #[serde(rename = "webp")]
    Webp,

}

impl ToString for ImageFormat {
    fn to_string(&self) -> String {
        match self {
            Self::Jpeg => String::from("jpeg"),
            Self::Webp => String::from("webp"),
        }
    }
}

impl Default for ImageFormat {
    fn default() -> ImageFormat {
        Self::Jpeg
    }
}

