/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobCommand {
    #[serde(rename = "start")]
    Start,
    #[serde(rename = "pause")]
    Pause,
    #[serde(rename = "resume")]
    Resume,
    #[serde(rename = "empty")]
    Empty,
    #[serde(rename = "clear-failed")]
    ClearFailed,

}

impl ToString for JobCommand {
    fn to_string(&self) -> String {
        match self {
            Self::Start => String::from("start"),
            Self::Pause => String::from("pause"),
            Self::Resume => String::from("resume"),
            Self::Empty => String::from("empty"),
            Self::ClearFailed => String::from("clear-failed"),
        }
    }
}

impl Default for JobCommand {
    fn default() -> JobCommand {
        Self::Start
    }
}

