/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobName {
    #[serde(rename = "thumbnailGeneration")]
    ThumbnailGeneration,
    #[serde(rename = "metadataExtraction")]
    MetadataExtraction,
    #[serde(rename = "videoConversion")]
    VideoConversion,
    #[serde(rename = "faceDetection")]
    FaceDetection,
    #[serde(rename = "facialRecognition")]
    FacialRecognition,
    #[serde(rename = "smartSearch")]
    SmartSearch,
    #[serde(rename = "duplicateDetection")]
    DuplicateDetection,
    #[serde(rename = "backgroundTask")]
    BackgroundTask,
    #[serde(rename = "storageTemplateMigration")]
    StorageTemplateMigration,
    #[serde(rename = "migration")]
    Migration,
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "sidecar")]
    Sidecar,
    #[serde(rename = "library")]
    Library,
    #[serde(rename = "notifications")]
    Notifications,

}

impl ToString for JobName {
    fn to_string(&self) -> String {
        match self {
            Self::ThumbnailGeneration => String::from("thumbnailGeneration"),
            Self::MetadataExtraction => String::from("metadataExtraction"),
            Self::VideoConversion => String::from("videoConversion"),
            Self::FaceDetection => String::from("faceDetection"),
            Self::FacialRecognition => String::from("facialRecognition"),
            Self::SmartSearch => String::from("smartSearch"),
            Self::DuplicateDetection => String::from("duplicateDetection"),
            Self::BackgroundTask => String::from("backgroundTask"),
            Self::StorageTemplateMigration => String::from("storageTemplateMigration"),
            Self::Migration => String::from("migration"),
            Self::Search => String::from("search"),
            Self::Sidecar => String::from("sidecar"),
            Self::Library => String::from("library"),
            Self::Notifications => String::from("notifications"),
        }
    }
}

impl Default for JobName {
    fn default() -> JobName {
        Self::ThumbnailGeneration
    }
}

