/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogLevel {
    #[serde(rename = "verbose")]
    Verbose,
    #[serde(rename = "debug")]
    Debug,
    #[serde(rename = "log")]
    Log,
    #[serde(rename = "warn")]
    Warn,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "fatal")]
    Fatal,

}

impl ToString for LogLevel {
    fn to_string(&self) -> String {
        match self {
            Self::Verbose => String::from("verbose"),
            Self::Debug => String::from("debug"),
            Self::Log => String::from("log"),
            Self::Warn => String::from("warn"),
            Self::Error => String::from("error"),
            Self::Fatal => String::from("fatal"),
        }
    }
}

impl Default for LogLevel {
    fn default() -> LogLevel {
        Self::Verbose
    }
}

