/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MemoryType {
    #[serde(rename = "on_this_day")]
    OnThisDay,

}

impl ToString for MemoryType {
    fn to_string(&self) -> String {
        match self {
            Self::OnThisDay => String::from("on_this_day"),
        }
    }
}

impl Default for MemoryType {
    fn default() -> MemoryType {
        Self::OnThisDay
    }
}

