/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PathType {
    #[serde(rename = "original")]
    Original,
    #[serde(rename = "preview")]
    Preview,
    #[serde(rename = "thumbnail")]
    Thumbnail,
    #[serde(rename = "encoded_video")]
    EncodedVideo,
    #[serde(rename = "sidecar")]
    Sidecar,
    #[serde(rename = "face")]
    Face,
    #[serde(rename = "profile")]
    Profile,

}

impl ToString for PathType {
    fn to_string(&self) -> String {
        match self {
            Self::Original => String::from("original"),
            Self::Preview => String::from("preview"),
            Self::Thumbnail => String::from("thumbnail"),
            Self::EncodedVideo => String::from("encoded_video"),
            Self::Sidecar => String::from("sidecar"),
            Self::Face => String::from("face"),
            Self::Profile => String::from("profile"),
        }
    }
}

impl Default for PathType {
    fn default() -> PathType {
        Self::Original
    }
}

