/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PathEntityType {
    #[serde(rename = "asset")]
    Asset,
    #[serde(rename = "person")]
    Person,
    #[serde(rename = "user")]
    User,

}

impl ToString for PathEntityType {
    fn to_string(&self) -> String {
        match self {
            Self::Asset => String::from("asset"),
            Self::Person => String::from("person"),
            Self::User => String::from("user"),
        }
    }
}

impl Default for PathEntityType {
    fn default() -> PathEntityType {
        Self::Asset
    }
}

