/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeopleResponseDto {
    #[serde(rename = "hidden")]
    pub hidden: i32,
    #[serde(rename = "people")]
    pub people: Vec<models::PersonResponseDto>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl PeopleResponseDto {
    pub fn new(hidden: i32, people: Vec<models::PersonResponseDto>, total: i32) -> PeopleResponseDto {
        PeopleResponseDto {
            hidden,
            people,
            total,
        }
    }
}

