/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReactionLevel {
    #[serde(rename = "album")]
    Album,
    #[serde(rename = "asset")]
    Asset,

}

impl ToString for ReactionLevel {
    fn to_string(&self) -> String {
        match self {
            Self::Album => String::from("album"),
            Self::Asset => String::from("asset"),
        }
    }
}

impl Default for ReactionLevel {
    fn default() -> ReactionLevel {
        Self::Album
    }
}

