/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReactionType {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "like")]
    Like,

}

impl ToString for ReactionType {
    fn to_string(&self) -> String {
        match self {
            Self::Comment => String::from("comment"),
            Self::Like => String::from("like"),
        }
    }
}

impl Default for ReactionType {
    fn default() -> ReactionType {
        Self::Comment
    }
}

