/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFacetCountResponseDto {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "value")]
    pub value: String,
}

impl SearchFacetCountResponseDto {
    pub fn new(count: i32, value: String) -> SearchFacetCountResponseDto {
        SearchFacetCountResponseDto {
            count,
            value,
        }
    }
}

