/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchSuggestionType {
    #[serde(rename = "country")]
    Country,
    #[serde(rename = "state")]
    State,
    #[serde(rename = "city")]
    City,
    #[serde(rename = "camera-make")]
    CameraMake,
    #[serde(rename = "camera-model")]
    CameraModel,

}

impl ToString for SearchSuggestionType {
    fn to_string(&self) -> String {
        match self {
            Self::Country => String::from("country"),
            Self::State => String::from("state"),
            Self::City => String::from("city"),
            Self::CameraMake => String::from("camera-make"),
            Self::CameraModel => String::from("camera-model"),
        }
    }
}

impl Default for SearchSuggestionType {
    fn default() -> SearchSuggestionType {
        Self::Country
    }
}

