/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerPingResponse {
    #[serde(rename = "res")]
    pub res: String,
}

impl ServerPingResponse {
    pub fn new(res: String) -> ServerPingResponse {
        ServerPingResponse {
            res,
        }
    }
}

