/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SharedLinkType {
    #[serde(rename = "ALBUM")]
    Album,
    #[serde(rename = "INDIVIDUAL")]
    Individual,

}

impl ToString for SharedLinkType {
    fn to_string(&self) -> String {
        match self {
            Self::Album => String::from("ALBUM"),
            Self::Individual => String::from("INDIVIDUAL"),
        }
    }
}

impl Default for SharedLinkType {
    fn default() -> SharedLinkType {
        Self::Album
    }
}

