/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagTypeEnum {
    #[serde(rename = "OBJECT")]
    Object,
    #[serde(rename = "FACE")]
    Face,
    #[serde(rename = "CUSTOM")]
    Custom,

}

impl ToString for TagTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Object => String::from("OBJECT"),
            Self::Face => String::from("FACE"),
            Self::Custom => String::from("CUSTOM"),
        }
    }
}

impl Default for TagTypeEnum {
    fn default() -> TagTypeEnum {
        Self::Object
    }
}

