/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeBucketSize {
    #[serde(rename = "DAY")]
    Day,
    #[serde(rename = "MONTH")]
    Month,

}

impl ToString for TimeBucketSize {
    fn to_string(&self) -> String {
        match self {
            Self::Day => String::from("DAY"),
            Self::Month => String::from("MONTH"),
        }
    }
}

impl Default for TimeBucketSize {
    fn default() -> TimeBucketSize {
        Self::Day
    }
}

