/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TranscodeHwAccel {
    #[serde(rename = "nvenc")]
    Nvenc,
    #[serde(rename = "qsv")]
    Qsv,
    #[serde(rename = "vaapi")]
    Vaapi,
    #[serde(rename = "rkmpp")]
    Rkmpp,
    #[serde(rename = "disabled")]
    Disabled,

}

impl ToString for TranscodeHwAccel {
    fn to_string(&self) -> String {
        match self {
            Self::Nvenc => String::from("nvenc"),
            Self::Qsv => String::from("qsv"),
            Self::Vaapi => String::from("vaapi"),
            Self::Rkmpp => String::from("rkmpp"),
            Self::Disabled => String::from("disabled"),
        }
    }
}

impl Default for TranscodeHwAccel {
    fn default() -> TranscodeHwAccel {
        Self::Nvenc
    }
}

