/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePartnerDto {
    #[serde(rename = "inTimeline")]
    pub in_timeline: bool,
}

impl UpdatePartnerDto {
    pub fn new(in_timeline: bool) -> UpdatePartnerDto {
        UpdatePartnerDto {
            in_timeline,
        }
    }
}

