/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.106.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VideoCodec {
    #[serde(rename = "h264")]
    H264,
    #[serde(rename = "hevc")]
    Hevc,
    #[serde(rename = "vp9")]
    Vp9,
    #[serde(rename = "av1")]
    Av1,

}

impl ToString for VideoCodec {
    fn to_string(&self) -> String {
        match self {
            Self::H264 => String::from("h264"),
            Self::Hevc => String::from("hevc"),
            Self::Vp9 => String::from("vp9"),
            Self::Av1 => String::from("av1"),
        }
    }
}

impl Default for VideoCodec {
    fn default() -> VideoCodec {
        Self::H264
    }
}

